import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Alpino = localFont({
  src: "../../public/fonts/Alpino-Variable.woff",
  variable: "--font-alpino",
  weight: "100 900",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Alpino.variable} antialiased overflow-x-hidden bg-yellow-400`}>
        {children}
        </body>
    </html>
  );
}
