import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactLenis } from "@/utils/lenis";
const Alpino = localFont({
  src: "../../public/fonts/Alpino-Variable.woff",
  variable: "--font-alpino",
  weight: "100 900",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${Alpino.variable} overflow-x-hidden bg-yellow-400 antialiased`}
        >
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
